#ifndef COMMON_INCLUDES_H_
#define COMMON_INCLUDES_H_

	#define OK -10
	#define NO_OK -11

	#define ERROR_ABRIR_PATH_INEXISTENTE 10001
	#define ERROR_ABRIR_ESPACIO_INSUFICIENTE_FM9 10002

	#define ERROR_ASIGNAR_ARCHIVO_NO_ABIERTO 20001
	#define ERROR_ASIGNAR_FALLO_SEGMENTO 20002
	#define ERROR_ASIGNAR_ESPACIO_INSUFICIENTE_FM9 20003
	#define ERROR_ASIGNAR_ARCHIVO_ES_ESCRIPTORIO 20004

	#define ERROR_FLUSH_ARCHIVO_NO_ABIERTO 30001
	#define ERROR_FLUSH_FALLO_SEGMENTO 30002
	#define ERROR_FLUSH_ESPACIO_INSUFICIENTE_MDJ 30003
	#define ERROR_FLUSH_ARCHIVO_NO_EXISTE_MDJ 30004

	#define ERROR_CLOSE_ARCHIVO_NO_ABIERTO 40001
	#define ERROR_CLOSE_FALLO_SEGMENTO 40002

	#define ERROR_CREAR_ARCHIVO_YA_EXISTENTE 50001
	#define ERROR_CREAR_ESPACIO_INSUFICIENTE_MDJ 50001

	#define ERROR_BORRAR_ARCHIVO_NO_EXISTE 60001


#endif /* COMMON_INCLUDES_H_ */
